[package]
exclude = ["*.jpg"]
name = "simdnoise"
version = "1.0.1"
authors = ["Jack Mott <jack.mott@gmail.com>"]
description = "SIMD accelerate noise library with runtime feature detection"
license = "Apache-2.0/MIT"
documentation = "https://docs.rs/simdnoise/"
readme = "README.md"
keywords = ["SIMD", "noise", "simplex", "perlin","performance"]
repository = "https://github.com/jackmott/rust-simd-noise"
categories = ["game-engines","multimedia::images"]

[dependencies]
rand = "0.5.1"
